name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        export current_tag=$(cat ./CurrentTag)
        docker build . --file Dockerfile --tag talkingpikachus/mobile_push_key:$current_tag

    - name: Login to ACR
      uses: aliyun/acr-login@v1
      with:
        login-server: https://registry.cn-qingdao.aliyuncs.com
        username: "${{ secrets.ACR_USERNAME }}"
        password: "${{ secrets.ACR_PASSWORD }}"
        
    - name: Push image
      run: |
        export current_tag=$(cat ./CurrentTag)
        docker push registry.cn-qingdao.aliyuncs.com/wei-z/demo:current_tag
