name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        current_tag=$(cat ./CurrentTag)
        docker build . --file Dockerfile --tag registry.cn-qingdao.aliyuncs.com/wei-z/mobile_push_key:$current_tag
        
    - name: push the Docker image
      run: |
        sudo docker login --username=${{secrets.ACR_USERNAME}} -p ${{secrets.ACR_PASSWORD}} registry.cn-qingdao.aliyuncs.com
        docker push registry.cn-qingdao.aliyuncs.com/wei-z/mobile_push_key:$current_tag

